### ISSUE TITLE
Console have some error text

### ISSUE THREAD

**Issue by Radiation-pi** [LOOHP/ImageFrame#20]
It may happer some times per day:

[Server thread/ERROR]: Could not pass event InventoryClickEvent to ImageFrame v1.7.4.2
java.lang.IllegalStateException: Item does not have map associated - check hasMapView() first!
	at com.google.common.base.Preconditions.checkState(Preconditions.java:512) ~[guava-32.1.1-jre.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.inventory.CraftMetaMap.getMapView(CraftMetaMap.java:152) ~[leaf-1.20.1.jar:git-Leaf-"6b48ad4"]
	at com.loohp.imageframe.utils.MapUtils.getItemMapView(MapUtils.java:286) ~[ImageFrame-1.7.4.2.jar:?]
	at com.loohp.imageframe.listeners.Events.onClick(Events.java:63) ~[ImageFrame-1.7.4.2.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1507.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[leaf-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[leaf-api-1.20.1-R0.1-SNAPSHOT.jar:git-Leaf-"6b48ad4"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:72) ~[leaf-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:60) ~[leaf-1.20.1.jar:git-Leaf-"6b48ad4"]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[leaf-1.20.1.jar:git-Leaf-"6b48ad4"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[leaf-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3320) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[leaf-1.20.1.jar:git-Leaf-"6b48ad4"]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1346) ~[leaf-1.20.1.jar:git-Leaf-"6b48ad4"]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:187) ~[leaf-1.20.1.jar:git-Leaf-"6b48ad4"]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1324) ~[leaf-1.20.1.jar:git-Leaf-"6b48ad4"]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1317) ~[leaf-1.20.1.jar:git-Leaf-"6b48ad4"]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1294) ~[leaf-1.20.1.jar:git-Leaf-"6b48ad4"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1183) ~[leaf-1.20.1.jar:git-Leaf-"6b48ad4"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:307) ~[leaf-1.20.1.jar:git-Leaf-"6b48ad4"]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]

**Comment by TobyMinceraft** [comment]
Have you considered tying base Paper instead of whatever that fork is?
