### ISSUE TITLE
Compatibility with Minecraft 1.20.2

### ISSUE THREAD

**Issue by Lobskii** [LOOHP/ImageFrame#25]
I just tried to do an update on a server to 1.20.2 and the console was spammed with messages from ImageFrame.
Changing it back to 1.20.1 stopped it, will there be an update to support 1.20.2 soon?

[15:58:56] [Server thread/WARN]: [ImageFrame] Task #1537 for ImageFrame v1.7.5.0 generated an exception
java.lang.NoClassDefFoundError: com/comphenix/protocol/ProtocolLibrary
	at com.loohp.imageframe.objectholders.AnimatedFakeMapManager.lambda$tick$1(AnimatedFakeMapManager.java:96) ~[?:?]
	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftFuture.run(CraftFuture.java:88) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3881-Spigot-17ca32d-f71a799]
	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3881-Spigot-17ca32d-f71a799]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1243) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3881-Spigot-17ca32d-f71a799]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:387) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3881-Spigot-17ca32d-f71a799]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1179) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3881-Spigot-17ca32d-f71a799]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:996) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3881-Spigot-17ca32d-f71a799]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:298) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3881-Spigot-17ca32d-f71a799]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.ProtocolLibrary
	... 9 more
[15:58:56] [Server thread/WARN]: [ImageFrame] Task #1538 for ImageFrame v1.7.5.0 generated an exception
java.lang.NoClassDefFoundError: com/comphenix/protocol/ProtocolLibrary
	at com.loohp.imageframe.objectholders.AnimatedFakeMapManager.lambda$tick$1(AnimatedFakeMapManager.java:96) ~[?:?]
	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftFuture.run(CraftFuture.java:88) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3881-Spigot-17ca32d-f71a799]
	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3881-Spigot-17ca32d-f71a799]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1243) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3881-Spigot-17ca32d-f71a799]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:387) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3881-Spigot-17ca32d-f71a799]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1179) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3881-Spigot-17ca32d-f71a799]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:996) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3881-Spigot-17ca32d-f71a799]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:298) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3881-Spigot-17ca32d-f71a799]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.ProtocolLibrary
	... 9 more
[15:58:56] [Server thread/WARN]: [ImageFrame] Task #1539 for ImageFrame v1.7.5.0 generated an exception
java.lang.NoClassDefFoundError: com/comphenix/protocol/ProtocolLibrary
	at com.loohp.imageframe.objectholders.AnimatedFakeMapManager.lambda$tick$1(AnimatedFakeMapManager.java:96) ~[?:?]
	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftFuture.run(CraftFuture.java:88) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3881-Spigot-17ca32d-f71a799]
	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3881-Spigot-17ca32d-f71a799]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1243) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3881-Spigot-17ca32d-f71a799]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:387) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3881-Spigot-17ca32d-f71a799]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1179) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3881-Spigot-17ca32d-f71a799]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:996) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3881-Spigot-17ca32d-f71a799]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:298) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3881-Spigot-17ca32d-f71a799]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.ProtocolLibrary
	... 9 more
[15:58:56] [Server thread/WARN]: [ImageFrame] Task #1540 for ImageFrame v1.7.5.0 generated an exception
java.lang.NoClassDefFoundError: com/comphenix/protocol/ProtocolLibrary
	at com.loohp.imageframe.objectholders.AnimatedFakeMapManager.lambda$tick$1(AnimatedFakeMapManager.java:96) ~[?:?]
	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftFuture.run(CraftFuture.java:88) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3881-Spigot-17ca32d-f71a799]
	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3881-Spigot-17ca32d-f71a799]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1243) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3881-Spigot-17ca32d-f71a799]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:387) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3881-Spigot-17ca32d-f71a799]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1179) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3881-Spigot-17ca32d-f71a799]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:996) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3881-Spigot-17ca32d-f71a799]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:298) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3881-Spigot-17ca32d-f71a799]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.ProtocolLibrary
	... 9 more

**Comment by LOOHP** [comment]
ProtocolLib not yet exists for 1.20.2, and ImageFrame will update to 1.20.2 in due time. Thank you.
