### ISSUE TITLE
Plugin ImageFrame v1.7.6.0 has failed to register events

### ISSUE THREAD

**Issue by adabugra** [LOOHP/ImageFrame#27]
[16:12:10 ERROR]: [ImageFrame] Plugin ImageFrame v1.7.6.0 has failed to register events for class com.loohp.imageframe.listeners.Events$ModernEvents because org/bukkit/event/world/EntitiesLoadEvent does not exist.
[16:12:10 ERROR]: [ImageFrame] Plugin ImageFrame v1.7.6.0 has failed to register events for class com.loohp.imageframe.objectholders.AnimatedFakeMapManager$ModernEvents because org/bukkit/event/world/EntitiesLoadEvent does not exist.
[16:12:10 WARN]: java.lang.NoSuchMethodException: net.minecraft.server.v1_16_R3.WorldServer.a(java.lang.String,net.minecraft.server.v1_16_R3.WorldMap)
[16:12:10 WARN]:        at java.base/java.lang.Class.getMethod(Class.java:2227)
[16:12:10 WARN]:        at com.loohp.imageframe.utils.MapUtils.<clinit>(MapUtils.java:145)
[16:12:10 WARN]:        at com.loohp.imageframe.objectholders.AnimatedFakeMapManager.handleEntity(AnimatedFakeMapManager.java:230)
[16:12:10 WARN]:        at com.loohp.imageframe.objectholders.AnimatedFakeMapManager.<init>(AnimatedFakeMapManager.java:75)
[16:12:10 WARN]:        at com.loohp.imageframe.ImageFrame.onEnable(ImageFrame.java:279)
[16:12:10 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[16:12:10 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[16:12:10 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[16:12:10 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[16:12:10 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[16:12:10 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:599)
[16:12:10 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298)
[16:12:10 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074)
[16:12:10 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[16:12:10 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by LOOHP** [comment]
Does the plugin still works?
