### ISSUE TITLE
Folia 1.20.1 server Imageframer 1.7.6

### ISSUE THREAD

**Issue by starmc63** [LOOHP/ImageFrame#28]
[04:33:29 ERROR]: Thread Folia Async Scheduler Thread #190 failed main thread check: Chunk getEntities call
java.lang.Throwable: null
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2673) ~[?:?]
        at net.minecraft.server.level.ServerLevel.getEntityOrPart(ServerLevel.java:2112) ~[?:?]
        at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:23) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.EntityUtilities.getNewEntityTracker(EntityUtilities.java:216) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.EntityUtilities.getEntityTrackerEntry(EntityUtilities.java:267) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.EntityUtilities.getTrackedPlayers(EntityUtilities.java:181) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.EntityUtilities.getEntityTrackers(EntityUtilities.java:164) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.getEntityTrackers(PacketFilterManager.java:414) ~[ProtocolLib.jar:?]
        at com.loohp.imageframe.objectholders.AnimatedFakeMapManager.run(AnimatedFakeMapManager.java:93) ~[ImageFrame-1.7.6.0.jar:?]
        at com.loohp.imageframe.objectholders.Scheduler.lambda$runTaskTimerAsynchronously$12(Scheduler.java:168) ~[ImageFrame-1.7.6.0.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[kaiiju-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[04:33:29 WARN]: [ImageFrame] Async task for ImageFrame v1.7.6.0 generated an exception
java.lang.IllegalStateException: Unable to invoke method public net.minecraft.world.entity.Entity net.minecraft.server.level.WorldServer.b(int)
        at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:25) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.EntityUtilities.getNewEntityTracker(EntityUtilities.java:216) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.EntityUtilities.getEntityTrackerEntry(EntityUtilities.java:267) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.EntityUtilities.getTrackedPlayers(EntityUtilities.java:181) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.EntityUtilities.getEntityTrackers(EntityUtilities.java:164) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.getEntityTrackers(PacketFilterManager.java:414) ~[ProtocolLib.jar:?]
        at com.loohp.imageframe.objectholders.AnimatedFakeMapManager.run(AnimatedFakeMapManager.java:93) ~[ImageFrame-1.7.6.0.jar:?]
        at com.loohp.imageframe.objectholders.Scheduler.lambda$runTaskTimerAsynchronously$12(Scheduler.java:168) ~[ImageFrame-1.7.6.0.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[kaiiju-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2673) ~[?:?]
        at net.minecraft.server.level.ServerLevel.getEntityOrPart(ServerLevel.java:2112) ~[?:?]
        at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:23) ~[ProtocolLib.jar:?]
        ... 11 more
[04:33:29 ERROR]: Thread Folia Async Scheduler Thread #189 failed main thread check: Chunk getEntities call
java.lang.Throwable: null
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2673) ~[?:?]
        at net.minecraft.server.level.ServerLevel.getEntityOrPart(ServerLevel.java:2112) ~[?:?]
        at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:23) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.EntityUtilities.getNewEntityTracker(EntityUtilities.java:216) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.EntityUtilities.getEntityTrackerEntry(EntityUtilities.java:267) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.EntityUtilities.getTrackedPlayers(EntityUtilities.java:181) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.EntityUtilities.getEntityTrackers(EntityUtilities.java:164) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.getEntityTrackers(PacketFilterManager.java:414) ~[ProtocolLib.jar:?]
        at com.loohp.imageframe.objectholders.AnimatedFakeMapManager.run(AnimatedFakeMapManager.java:93) ~[ImageFrame-1.7.6.0.jar:?]
        at com.loohp.imageframe.objectholders.Scheduler.lambda$runTaskTimerAsynchronously$12(Scheduler.java:168) ~[ImageFrame-1.7.6.0.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[kaiiju-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[04:33:29 WARN]: [ImageFrame] Async task for ImageFrame v1.7.6.0 generated an exception
java.lang.IllegalStateException: Unable to invoke method public net.minecraft.world.entity.Entity net.minecraft.server.level.WorldServer.b(int)
        at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:25) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.EntityUtilities.getNewEntityTracker(EntityUtilities.java:216) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.EntityUtilities.getEntityTrackerEntry(EntityUtilities.java:267) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.EntityUtilities.getTrackedPlayers(EntityUtilities.java:181) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.EntityUtilities.getEntityTrackers(EntityUtilities.java:164) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.getEntityTrackers(PacketFilterManager.java:414) ~[ProtocolLib.jar:?]
        at com.loohp.imageframe.objectholders.AnimatedFakeMapManager.run(AnimatedFakeMapManager.java:93) ~[ImageFrame-1.7.6.0.jar:?]
        at com.loohp.imageframe.objectholders.Scheduler.lambda$runTaskTimerAsynchronously$12(Scheduler.java:168) ~[ImageFrame-1.7.6.0.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[kaiiju-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2673) ~[?:?]
        at net.minecraft.server.level.ServerLevel.getEntityOrPart(ServerLevel.java:2112) ~[?:?]
        at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:23) ~[ProtocolLib.jar:?]
        ... 11 more

**Comment by nyancat-hu** [comment]
I have blocked several functions that caused errors, and the plugin is still working properly. I am not sure what the consequences will be, but the backend is much cleaner. If you need it, you can download it here.
https://github.com/nyancat-hu/ImageFrame/releases/tag/folia-1.0.0

**Comment by LOOHP** [comment]
I've made a fix for this but haven't released it yet, it should come with the 1.20.4 support update soon, likely within a day.

**Comment by LOOHP** [comment]
Should already be fixed now.
