### ISSUE TITLE
Error enabling ImageFrame v1.7.6.0

### ISSUE THREAD

**Issue by Waffelo** [LOOHP/ImageFrame#29]
I have stumbled upon an error while adding the plugin to my server with `paper-1.20.2-240`. I also got the latest version of ProtocolLib. I get this error while running any command:

![image](https://github.com/LOOHP/ImageFrame/assets/47056551/867cb6e5-e57b-4d30-b904-74ad35be6fa1)

When I look into the latest error logs for ImageFrame, I get:
```
$ cat logs/latest.log | grep Image

[15:17:38] [Server thread/INFO]: [ImageFrame] Loading server plugin ImageFrame v1.7.6.0
[15:17:41] [Server thread/INFO]: [ImageFrame] Enabling ImageFrame v1.7.6.0
[15:17:41] [Server thread/ERROR]: Error occurred while enabling ImageFrame v1.7.6.0 (Is it up to date?)
        at com.loohp.imageframe.objectholders.RateLimitedPacketSendingManager.<init>(RateLimitedPacketSendingManager.java:51) ~[ImageFrame-1.7.6.0.jar:?]
        at com.loohp.imageframe.ImageFrame.onEnable(ImageFrame.java:280) ~[ImageFrame-1.7.6.0.jar:?]
[15:17:41] [Server thread/INFO]: [ImageFrame] Disabling ImageFrame v1.7.6.0
[15:17:41] [Server thread/INFO]: [ImageFrame] Unable to save ImageMapManager data in /usr/local/minecraft/DrgnCraft/plugins/ImageFrame/data/deletedMaps.bin
[15:17:41] [Server thread/WARN]: java.nio.file.NoSuchFileException: plugins/ImageFrame/data/deletedMaps.bin
[15:17:41] [Server thread/WARN]:        at ImageFrame-1.7.6.0.jar//com.loohp.imageframe.objectholders.ImageMapManager.saveDeletedMaps(ImageMapManager.java:290)
[15:17:41] [Server thread/WARN]:        at ImageFrame-1.7.6.0.jar//com.loohp.imageframe.objectholders.ImageMapManager.close(ImageMapManager.java:107)
[15:17:41] [Server thread/WARN]:        at ImageFrame-1.7.6.0.jar//com.loohp.imageframe.ImageFrame.onDisable(ImageFrame.java:295)
[15:17:41] [Server thread/INFO]: [ImageFrame] ImageFrame has been Disabled!
org.bukkit.command.CommandException: Cannot execute command 'imageframe' in plugin ImageFrame v1.7.6.0 - plugin is disabled.
```

And when I look into the latest error logs for ProtocolLib, I get:
```
$ cat logs/latest.log | grep Protocol

[15:28:36] [Server thread/INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.1.0
[15:28:36] [Server thread/WARN]: [ProtocolLib] Version (MC: 1.20.2) has not yet been tested! Proceed with caution.
[15:28:37] [Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
        at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
    com.comphenix.protocol.ProtocolLib@2e4cacfd[
      commandProtocol=<null>
      file=plugins/ProtocolLib.jar
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.1.0, pluginEnabled=false, url=plugins/ProtocolLib.jar}
      configFile=plugins/ProtocolLib/config.yml
    ProtocolLib v5.1.0
[15:28:37] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v5.1.0
[15:28:37] [Server thread/ERROR]: *** ProtocolLib does not support plugin reloaders! ***
[15:28:37] [Server thread/INFO]: [ProtocolLib] Disabling ProtocolLib v5.1.0
java.lang.NoClassDefFoundError: com/comphenix/protocol/ProtocolLibrary
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.ProtocolLibrary

```

**Comment by LOOHP** [comment]
You likely aren't using the latest ProtocolLib DEV BUILD. Make sure it is the dev build not the release version.

**Comment by Waffelo** [comment]
I have installed the latest dev build and it works! Thank you! :D
