### ISSUE TITLE
error folia 1.20.2

### ISSUE THREAD

**Issue by xiaoluofa** [LOOHP/ImageFrame#34]
[15:37:22 WARN]: [ImageFrame] Async task for ImageFrame v1.7.6.0 generated an exception
java.lang.IllegalStateException: Unable to invoke method public net.minecraft.world.entity.Entity net.minecraft.server.level.WorldServer.b(int)
        at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:25) ~[ProtocolLib .jar:?]
        at com.comphenix.protocol.injector.EntityUtilities.getNewEntityTracker(EntityUtilities.java:216) ~[ProtocolLib .jar:?]
        at com.comphenix.protocol.injector.EntityUtilities.getEntityTrackerEntry(EntityUtilities.java:267) ~[ProtocolLib .jar:?]
        at com.comphenix.protocol.injector.EntityUtilities.getTrackedPlayers(EntityUtilities.java:181) ~[ProtocolLib .jar:?]
        at com.comphenix.protocol.injector.EntityUtilities.getEntityTrackers(EntityUtilities.java:164) ~[ProtocolLib .jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.getEntityTrackers(PacketFilterManager.java:414) ~[ProtocolLib .jar:?]
        at com.loohp.imageframe.objectholders.AnimatedFakeMapManager.run(AnimatedFakeMapManager.java:93) ~[【图片】ImageFrame-1.7.6.0.jar:?]
        at com.loohp.imageframe.objectholders.Scheduler.lambda$runTaskTimerAsynchronously$12(Scheduler.java:168) ~[【图 片】ImageFrame-1.7.6.0.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[folia-1.20.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2813) ~[?:?]
        at net.minecraft.server.level.ServerLevel.getEntityOrPart(ServerLevel.java:2245) ~[?:?]
        at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:23) ~[ProtocolLib .jar:?]
        ... 11 more
[15:37:22 ERROR]: Thread Folia Async Scheduler Thread #13 failed main thread check: Chunk getEntities call
java.lang.Throwable: null
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2813) ~[?:?]
        at net.minecraft.server.level.ServerLevel.getEntityOrPart(ServerLevel.java:2245) ~[?:?]
        at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:23) ~[ProtocolLib .jar:?]
        at com.comphenix.protocol.injector.EntityUtilities.getNewEntityTracker(EntityUtilities.java:216) ~[ProtocolLib .jar:?]
        at com.comphenix.protocol.injector.EntityUtilities.getEntityTrackerEntry(EntityUtilities.java:267) ~[ProtocolLib .jar:?]
        at com.comphenix.protocol.injector.EntityUtilities.getTrackedPlayers(EntityUtilities.java:181) ~[ProtocolLib .jar:?]
        at com.comphenix.protocol.injector.EntityUtilities.getEntityTrackers(EntityUtilities.java:164) ~[ProtocolLib .jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.getEntityTrackers(PacketFilterManager.java:414) ~[ProtocolLib .jar:?]
        at com.loohp.imageframe.objectholders.AnimatedFakeMapManager.run(AnimatedFakeMapManager.java:93) ~[【图片】ImageFrame-1.7.6.0.jar:?]
        at com.loohp.imageframe.objectholders.Scheduler.lambda$runTaskTimerAsynchronously$12(Scheduler.java:168) ~[【图 片】ImageFrame-1.7.6.0.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[folia-1.20.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by KeiBoogie** [comment]
Same issue, please fix!
