### ISSUE TITLE
Plugin won't start with Paper 1.20.4

### ISSUE THREAD

**Issue by ColormaticStudios** [LOOHP/ImageFrame#36]
```
[20:18:22 INFO]: [ImageFrame] Enabling ImageFrame v1.7.6.0                                                     
[20:18:22 INFO]: [ImageFrame] This version of minecraft is unsupported! (Unsupported)                          
[20:18:22 INFO]: [ImageFrame] ImageFrame has hooked into ViaVersion!                                           
[20:18:22 ERROR]: Error occurred while enabling ImageFrame v1.7.6.0 (Is it up to date?)                        
java.lang.NoClassDefFoundError: com/comphenix/protocol/ProtocolLibrary                                         
        at com.loohp.imageframe.objectholders.RateLimitedPacketSendingManager.<init>(RateLimitedPacketSendingMa
nager.java:51) ~[ImageFrame-1.7.6.0.jar:?]                                                                     
        at com.loohp.imageframe.ImageFrame.onEnable(ImageFrame.java:280) ~[ImageFrame-1.7.6.0.jar:?]           
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.4-R0.1-SNAPSHOT.j
ar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.j
ava:190) ~[paper-1.20.4.jar:git-Paper-378]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
 ~[paper-1.20.4.jar:git-Paper-378]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-
R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:637) ~[paper-1.20.4.jar:gi
t-Paper-378]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:548) ~[paper-1.20.4.jar:g
it-Paper-378]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:673) ~[paper-1.20.4.jar:git-Pap
er-378]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:433) ~[paper-1.20.4.jar:git-Pape
r-378]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.4.j
ar:git-Paper-378]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1132) ~[paper-1.20.4.jar:git-Pap
er-378]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-
Paper-378]
        at java.lang.Thread.run(Thread.java:833) ~[?:?] 
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.ProtocolLibrary
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.20.4-R
0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.20.4-R0
.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 14 more
[20:18:22 INFO]: [ImageFrame] Disabling ImageFrame v1.7.6.0
[20:18:22 INFO]: [ImageFrame] ImageFrame has been Disabled!

```

**Comment by kdkasad** [comment]
The following line from your log would suggest that you don't have [ProtocolLib](https://github.com/dmulloy2/ProtocolLib) installed, which is required for ImageFrame:
```
java.lang.NoClassDefFoundError: com/comphenix/protocol/ProtocolLibrary
```

**Comment by LOOHP** [comment]
Indeed, but it is no longer the case. Modern versions of ImageFrame no longer require ProtocolLib, which means this can be closed! :)
