### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by Cestis** [LOOHP/ImageFrame#38]
Purpur 1.20.1

> [15:08:14 WARN]: [ImageFrame] Plugin ImageFrame v1.7.7.0 generated an exception while executing task 27
> java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.ReferenceArrayList.get(int)" because "this.wrapped" is null
>         at it.unimi.dsi.fastutil.objects.ReferenceOpenHashSet$SetIterator.next(ReferenceOpenHashSet.java:514) ~[fastutil-8.5.9.jar:?]
>         at com.comphenix.protocol.injector.EntityUtilities.getEntityTrackers(EntityUtilities.java:167) ~[ProtocolLib.jar:?]
>         at com.comphenix.protocol.injector.PacketFilterManager.getEntityTrackers(PacketFilterManager.java:414) ~[ProtocolLib.jar:?]
>         at com.loohp.imageframe.objectholders.AnimatedFakeMapManager.getEntityTrackers(AnimatedFakeMapManager.java:93) ~[ImageFrame-1.7.7.0.jar:?]
>         at com.loohp.imageframe.objectholders.AnimatedFakeMapManager.run(AnimatedFakeMapManager.java:126) ~[ImageFrame-1.7.7.0.jar:?]
>         at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.1.jar:git-Purpur-2050]
>         at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.1.jar:git-Purpur-2050]
>         at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.1.jar:?]
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
>         at java.lang.Thread.run(Thread.java:1589) ~[?:?]

**Comment by LilyKensa** [comment]
It's probably a compatibility issue with `ProtocolLib`.
