### ISSUE TITLE
Stacktrace when doing specific command

### ISSUE THREAD

**Issue by LcyDev** [LOOHP/ImageFrame#5]
[14:06:49] [Server thread/INFO]: LioPro_3p issued server command: /imageframe create BatistaPaiting https://imgur.com/P1ecjZc 4 4 combined

I know this is because the image doesn't link directly to the img but i think this full error is not nice

```cs
[14:06:50] [Craft Scheduler Thread - 14995 - ImageFrame/WARN]: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Unable to read or download image, does this url directly links to an image? (https://imgur.com/P1ecjZc)
[14:06:50] [Craft Scheduler Thread - 14995 - ImageFrame/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
[14:06:50] [Craft Scheduler Thread - 14995 - ImageFrame/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[14:06:50] [Craft Scheduler Thread - 14995 - ImageFrame/WARN]: 	at ImageFrame-1.6.2.0.jar//com.loohp.imageframe.Commands.lambda$onCommand$5(Commands.java:184)
[14:06:50] [Craft Scheduler Thread - 14995 - ImageFrame/WARN]: 	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101)
[14:06:50] [Craft Scheduler Thread - 14995 - ImageFrame/WARN]: 	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[14:06:50] [Craft Scheduler Thread - 14995 - ImageFrame/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[14:06:50] [Craft Scheduler Thread - 14995 - ImageFrame/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[14:06:50] [Craft Scheduler Thread - 14995 - ImageFrame/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[14:06:50] [Craft Scheduler Thread - 14995 - ImageFrame/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[14:06:50] [Craft Scheduler Thread - 14995 - ImageFrame/WARN]: Caused by: java.lang.RuntimeException: Unable to read or download image, does this url directly links to an image? (https://imgur.com/P1ecjZc)
[14:06:50] [Craft Scheduler Thread - 14995 - ImageFrame/WARN]: 	at ImageFrame-1.6.2.0.jar//com.loohp.imageframe.objectholders.URLStaticImageMap.update(URLStaticImageMap.java:208)
[14:06:50] [Craft Scheduler Thread - 14995 - ImageFrame/WARN]: 	at ImageFrame-1.6.2.0.jar//com.loohp.imageframe.objectholders.URLStaticImageMap.lambda$create$2(URLStaticImageMap.java:91)
[14:06:50] [Craft Scheduler Thread - 14995 - ImageFrame/WARN]: 	at ImageFrame-1.6.2.0.jar//com.loohp.imageframe.utils.FutureUtils.lambda$callAsyncMethod$1(FutureUtils.java:62)
[14:06:50] [Craft Scheduler Thread - 14995 - ImageFrame/WARN]: 	... 6 more
```

**Comment by LOOHP** [comment]
A clearer error is better than no information at all. What if on another day, you used a direct link but an error occur? It would be much easier for me to fix bugs.
