### ISSUE TITLE
Connection Timing Out

### ISSUE THREAD

**Issue by bobbyl140** [LOOHP/ImageFrame#52]
I just found this plugin, which seems to be the only one like this with 1.20 support. I uploaded an image to my web server, loaded it successfully in a browser, selected some item frames, then ran `/if create test <url> selection`. It took a few minutes to show any sign of activity, then spit out the following in the console:
```
[15:06:36 WARN]: java.util.concurrent.ExecutionException: java.net.ConnectException: Connection timed out
[15:06:36 WARN]:        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
[15:06:36 WARN]:        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[15:06:36 WARN]:        at ImageFrame-1.7.7.0.jar//com.loohp.imageframe.Commands.lambda$onCommand$5(Commands.java:207)
[15:06:36 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[15:06:36 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[15:06:36 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[15:06:36 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[15:06:36 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[15:06:36 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[15:06:37 WARN]: Caused by: java.net.ConnectException: Connection timed out
[15:06:37 WARN]:        at java.base/sun.nio.ch.Net.connect0(Native Method)
[15:06:37 WARN]:        at java.base/sun.nio.ch.Net.connect(Net.java:579)
[15:06:37 WARN]:        at java.base/sun.nio.ch.Net.connect(Net.java:568)
[15:06:37 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:593)
[15:06:37 WARN]:        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
[15:06:37 WARN]:        at java.base/java.net.Socket.connect(Socket.java:633)
[15:06:37 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
[15:06:37 WARN]:        at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174)
[15:06:37 WARN]:        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
[15:06:37 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:533)
[15:06:37 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:638)
[15:06:37 WARN]:        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
[15:06:37 WARN]:        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
[15:06:37 WARN]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
[15:06:37 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
[15:06:37 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
[15:06:37 WARN]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
[15:06:37 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
[15:06:37 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[15:06:37 WARN]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[15:06:37 WARN]:        at ImageFrame-1.7.7.0.jar//com.loohp.imageframe.utils.HTTPRequestUtils.getInputStream(HTTPRequestUtils.java:69)
[15:06:37 WARN]:        at ImageFrame-1.7.7.0.jar//com.loohp.imageframe.utils.HTTPRequestUtils.download(HTTPRequestUtils.java:73)
[15:06:37 WARN]:        at ImageFrame-1.7.7.0.jar//com.loohp.imageframe.objectholders.URLStaticImageMap.update(URLStaticImageMap.java:208)
[15:06:37 WARN]:        at ImageFrame-1.7.7.0.jar//com.loohp.imageframe.objectholders.URLStaticImageMap.lambda$create$2(URLStaticImageMap.java:92)
[15:06:37 WARN]:        at ImageFrame-1.7.7.0.jar//com.loohp.imageframe.utils.FutureUtils.lambda$callAsyncMethod$5(FutureUtils.java:138)
[15:06:37 WARN]:        ... 6 more
```

**Comment by LOOHP** [comment]
Perhaps your webserver is blocking the request? Have you tried whether the same thing happens with other image hosting? (Don't try imgur)
