### ISSUE TITLE
can't work on folia 1.20.4 

### ISSUE THREAD

**Issue by SeemWind** [LOOHP/ImageFrame#57]
```
[12:08:22 WARN]: [ImageFrame] Async task for ImageFrame v1.7.8.3 generated an exception
java.lang.IllegalStateException: Accessing entity state off owning region's thread
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:79) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftItemFrame.getHandle(CraftItemFrame.java:169) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftItemFrame.getHandle(CraftItemFrame.java:14) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftEntity.equals(CraftEntity.java:567) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:244) ~[guava-32.1.2-jre.jar:?]
        at com.google.common.collect.RegularImmutableMap.fromEntryArrayCheckingBucketOverflow(RegularImmutableMap.java:133) ~[guava-32.1.2-jre.jar:?]
        at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:95) ~[guava-32.1.2-jre.jar:?]
        at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:572) ~[guava-32.1.2-jre.jar:?]
        at com.google.common.collect.ImmutableMap$Builder.buildOrThrow(ImmutableMap.java:600) ~[guava-32.1.2-jre.jar:?]
        at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:587) ~[guava-32.1.2-jre.jar:?]
        at com.loohp.imageframe.objectholders.AnimatedFakeMapManager.buildAllItemFrameInfo(AnimatedFakeMapManager.java:151) ~[ImageFrame-1.7.8.3.jar:?]
        at com.loohp.imageframe.objectholders.AnimatedFakeMapManager.run(AnimatedFakeMapManager.java:155) ~[ImageFrame-1.7.8.3.jar:?]
        at com.loohp.imageframe.objectholders.Scheduler.lambda$runTaskTimerAsynchronously$12(Scheduler.java:168) ~[ImageFrame-1.7.8.3.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[folia-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1570) ~[?:?]
[12:08:23 ERROR]: Thread Folia Async Scheduler Thread #5 failed main thread check: Accessing entity state off owning region's thread
java.lang.Throwable: null
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:78) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftItemFrame.getHandle(CraftItemFrame.java:169) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftItemFrame.getHandle(CraftItemFrame.java:14) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftEntity.equals(CraftEntity.java:567) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:244) ~[guava-32.1.2-jre.jar:?]
        at com.google.common.collect.RegularImmutableMap.fromEntryArrayCheckingBucketOverflow(RegularImmutableMap.java:133) ~[guava-32.1.2-jre.jar:?]
        at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:95) ~[guava-32.1.2-jre.jar:?]
        at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:572) ~[guava-32.1.2-jre.jar:?]
        at com.google.common.collect.ImmutableMap$Builder.buildOrThrow(ImmutableMap.java:600) ~[guava-32.1.2-jre.jar:?]
        at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:587) ~[guava-32.1.2-jre.jar:?]
        at com.loohp.imageframe.objectholders.AnimatedFakeMapManager.buildAllItemFrameInfo(AnimatedFakeMapManager.java:151) ~[ImageFrame-1.7.8.3.jar:?]
        at com.loohp.imageframe.objectholders.AnimatedFakeMapManager.run(AnimatedFakeMapManager.java:155) ~[ImageFrame-1.7.8.3.jar:?]
        at com.loohp.imageframe.objectholders.Scheduler.lambda$runTaskTimerAsynchronously$12(Scheduler.java:168) ~[ImageFrame-1.7.8.3.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[folia-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1570) ~[?:?]
```

**Comment by SeemWind** [comment]
but the plugin of version 1.7.7.0 works well, and I noticed that you delete dependence of protocollib, maybe that caused?

**Comment by LOOHP** [comment]
Might be related to #55.
