### ISSUE TITLE
java.io.IOException: Unable to download image

### ISSUE THREAD

**Issue by junebug12851** [LOOHP/ImageFrame#68]
I'm getting this error when trying to download any image. At first I tried a jpg image, then i tried it on imgur and used the direct image link. I then tried some png and other jpg images. All couldn't be used and had same error. This is self-hosted and I checked folder permissions, the folders are owned by the same user that's running minecraft so there shouldn't be any permission issues. I couldn't find any other help online.

Java Version
```
openjdk version "21.0.4" 2024-07-16
OpenJDK Runtime Environment (build 21.0.4+7-Ubuntu-1ubuntu224.04)
OpenJDK 64-Bit Server VM (build 21.0.4+7-Ubuntu-1ubuntu224.04, mixed mode, sharing)
```

Minecraft Version 1.21

ImageFrame version, I tried both `ImageFrame-1.7.9` shown below and the newest `ImageFrame-1.7.10`, both show the same error message
![image](https://github.com/user-attachments/assets/c69a5981-2c37-4f24-a19a-00f0328be541)

```
[19:35:43 WARN]: java.io.IOException: Unable to download image. Make sure you are using a direct link to the image, they usually ends with a file extension like ".png". Dispatcher: ###### URL: "######"
[19:35:43 WARN]:        at ImageFrame-1.7.9.0.jar//com.loohp.imageframe.Commands.lambda$onCommand$5(Commands.java:257)
[19:35:43 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86)
[19:35:43 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[19:35:43 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[19:35:43 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[19:35:43 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[19:35:43 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[19:35:43 WARN]: Caused by: java.util.concurrent.ExecutionException: java.net.MalformedURLException: no protocol: "######"
[19:35:43 WARN]:        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
[19:35:43 WARN]:        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[19:35:43 WARN]:        at ImageFrame-1.7.9.0.jar//com.loohp.imageframe.Commands.lambda$onCommand$5(Commands.java:221)
[19:35:43 WARN]:        ... 6 more
[19:35:43 WARN]: Caused by: java.net.MalformedURLException: no protocol: "https://######"
[19:35:43 WARN]:        at java.base/java.net.URL.<init>(URL.java:772)
[19:35:43 WARN]:        at java.base/java.net.URL.<init>(URL.java:654)
[19:35:43 WARN]:        at java.base/java.net.URL.<init>(URL.java:590)
[19:35:43 WARN]:        at ImageFrame-1.7.9.0.jar//com.loohp.imageframe.utils.HTTPRequestUtils.getInputStream(HTTPRequestUtils.java:63)
[19:35:43 WARN]:        at ImageFrame-1.7.9.0.jar//com.loohp.imageframe.utils.HTTPRequestUtils.download(HTTPRequestUtils.java:73)
[19:35:43 WARN]:        at ImageFrame-1.7.9.0.jar//com.loohp.imageframe.objectholders.URLStaticImageMap.update(URLStaticImageMap.java:228)
[19:35:43 WARN]:        at ImageFrame-1.7.9.0.jar//com.loohp.imageframe.objectholders.URLStaticImageMap.lambda$create$2(URLStaticImageMap.java:92)
[19:35:43 WARN]:        at ImageFrame-1.7.9.0.jar//com.loohp.imageframe.utils.FutureUtils.lambda$callAsyncMethod$5(FutureUtils.java:138)
[19:35:43 WARN]:        ... 6 more```

**Comment by LilyKensa** [comment]
The error indicates that you're trying to download `https://######`, which obviously isn't a valid URL.
