### ISSUE TITLE
Paper 1.21.1 java.lang.RuntimeException: java.nio.file.AccessDeniedException

### ISSUE THREAD

**Issue by false-fox** [LOOHP/ImageFrame#75]
Running a paper 1.21.1 on docker server in a debian based system. Image frame disables itself due to an access denied exception right as paper starts loading it

Log:
`` [11:07:56] [Server thread/ERROR]: Error occurred while enabling ImageFrame v1.7.10.1 (Is it up to date?)
java.lang.RuntimeException: java.nio.file.AccessDeniedException: plugins/ImageFrame/config.yml
	at ImageFrame-1.7.10.1.jar/com.loohp.imageframe.config.Config.save(Config.java:163) ~[ImageFrame-1.7.10.1.jar:?]
	at ImageFrame-1.7.10.1.jar/com.loohp.imageframe.config.Config.save(Config.java:156) ~[ImageFrame-1.7.10.1.jar:?]
	at ImageFrame-1.7.10.1.jar/com.loohp.imageframe.config.Config.<init>(Config.java:140) ~[ImageFrame-1.7.10.1.jar:?]
	at ImageFrame-1.7.10.1.jar/com.loohp.imageframe.config.Config.loadConfig(Config.java:68) ~[ImageFrame-1.7.10.1.jar:?]
	at ImageFrame-1.7.10.1.jar/com.loohp.imageframe.config.Config.loadConfig(Config.java:74) ~[ImageFrame-1.7.10.1.jar:?]
	at ImageFrame-1.7.10.1.jar/com.loohp.imageframe.ImageFrame.onEnable(ImageFrame.java:277) ~[ImageFrame-1.7.10.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.1.jar:1.21.1-45-5b2c43e]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-45-5b2c43e]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.1.jar:1.21.1-45-5b2c43e]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.1.jar:1.21.1-45-5b2c43e]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754) ~[paper-1.21.1.jar:1.21.1-45-5b2c43e]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516) ~[paper-1.21.1.jar:1.21.1-45-5b2c43e]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.1.jar:1.21.1-45-5b2c43e]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[paper-1.21.1.jar:1.21.1-45-5b2c43e]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-45-5b2c43e]
	at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.nio.file.AccessDeniedException: plugins/ImageFrame/config.yml
	at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source) ~[?:?]
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(Unknown Source) ~[?:?]
	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(Unknown Source) ~[?:?]
	at java.base/java.nio.file.Files.newOutputStream(Unknown Source) ~[?:?]
	at ImageFrame-1.7.10.1.jar/com.loohp.imageframe.libs.org.simpleyaml.configuration.file.FileConfiguration.save(FileConfiguration.java:62) ~[ImageFrame-1.7.10.1.jar:?]
	at ImageFrame-1.7.10.1.jar/com.loohp.imageframe.config.Config.save(Config.java:161) ~[ImageFrame-1.7.10.1.jar:?]
	... 17 more
[11:07:56] [Server thread/INFO]: [ImageFrame] Disabling ImageFrame v1.7.10.1
[11:07:56] [Server thread/INFO]: [ImageFrame] ImageFrame has been Disabled!
``

**Comment by false-fox** [comment]
deleting the Plugins/ImageFrame/ folder solved the issue. closing :)
