### ISSUE TITLE
1.21.1 imageframe error, how to fix it?

### ISSUE THREAD

**Issue by newhajinyoon** [LOOHP/ImageFrame#85]
```
[18:38:07 INFO]: [ImageFrame] Enabling ImageFrame v1.7.10.0
[18:38:08 INFO]: [ImageFrame] ImageFrame has hooked into ViaVersion!
[18:38:08 WARN]: Error while reading map color cache
[18:38:08 WARN]: java.util.zip.ZipException: incorrect header check
[18:38:08 WARN]:        at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:181)
[18:38:08 WARN]:        at java.base/java.io.InputStream.readNBytes(InputStream.java:412)
[18:38:08 WARN]:        at java.base/java.io.InputStream.readAllBytes(InputStream.java:349)
[18:38:08 WARN]:        at org.bukkit.craftbukkit.map.CraftMapColorCache.initCache(CraftMapColorCache.java:68)
[18:38:08 WARN]:        at org.bukkit.craftbukkit.map.CraftMapColorCache.isCached(CraftMapColorCache.java:149)
[18:38:08 WARN]:        at org.bukkit.map.MapPalette.matchColor(MapPalette.java:247)
[18:38:08 WARN]:        at org.bukkit.map.MapPalette.matchColor(MapPalette.java:232)
[18:38:08 WARN]:        at ImageFrame-1.7.10.0 (1).jar//com.loohp.imageframe.utils.MapUtils.<clinit>(MapUtils.java:70)
[18:38:08 WARN]:        at ImageFrame-1.7.10.0 (1).jar//com.loohp.imageframe.objectholders.AnimatedFakeMapManager.handleEntity(AnimatedFakeMapManager.java:295)
[18:38:08 WARN]:        at ImageFrame-1.7.10.0 (1).jar//com.loohp.imageframe.objectholders.AnimatedFakeMapManager.<init>(AnimatedFakeMapManager.java:83)
[18:38:08 WARN]:        at ImageFrame-1.7.10.0 (1).jar//com.loohp.imageframe.ImageFrame.onEnable(ImageFrame.java:306)
[18:38:08 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[18:38:08 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[18:38:08 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[18:38:08 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[18:38:08 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:654)
[18:38:08 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:603)
[18:38:08 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:757)
[18:38:08 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:519)
[18:38:08 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:363)
[18:38:08 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230)
[18:38:08 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333)
[18:38:08 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[18:38:08 ERROR]: Error occurred while enabling ImageFrame v1.7.10.0 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at ImageFrame-1.7.10.0 (1).jar/com.loohp.imageframe.objectholders.AnimatedFakeMapManager.handleEntity(AnimatedFakeMapManager.java:295) ~[ImageFrame-1.7.10.0 (1).jar:?]
        at ImageFrame-1.7.10.0 (1).jar/com.loohp.imageframe.objectholders.AnimatedFakeMapManager.<init>(AnimatedFakeMapManager.java:83) ~[ImageFrame-1.7.10.0 (1).jar:?]
        at ImageFrame-1.7.10.0 (1).jar/com.loohp.imageframe.ImageFrame.onEnable(ImageFrame.java:306) ~[ImageFrame-1.7.10.0 (1).jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:654) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:603) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:757) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:519) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:363) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalStateException: Cache not build jet
        at com.google.common.base.Preconditions.checkState(Preconditions.java:512) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.craftbukkit.map.CraftMapColorCache.matchColor(CraftMapColorCache.java:154) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at org.bukkit.map.MapPalette.matchColor(MapPalette.java:248) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.map.MapPalette.matchColor(MapPalette.java:232) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at ImageFrame-1.7.10.0 (1).jar/com.loohp.imageframe.utils.MapUtils.<clinit>(MapUtils.java:70) ~[ImageFrame-1.7.10.0 (1).jar:?]
        ... 15 more
[18:38:08 INFO]: [ImageFrame] Disabling ImageFrame v1.7.10.0
[18:38:08 INFO]: [ImageFrame] Unable to save ImageMapManager data in C:\Users\Administrator\Desktop\Season1\survival\plugins\ImageFrame\data\deletedMaps.bin
[18:38:08 WARN]: java.nio.file.NoSuchFileException: plugins\ImageFrame\data\deletedMaps.bin
[18:38:08 WARN]:        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
[18:38:08 WARN]:        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[18:38:08 WARN]:        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[18:38:08 WARN]:        at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:234)
[18:38:08 WARN]:        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:482)
[18:38:08 WARN]:        at java.base/java.nio.file.Files.newOutputStream(Files.java:227)
[18:38:08 WARN]:        at ImageFrame-1.7.10.0 (1).jar//com.loohp.imageframe.objectholders.ImageMapManager.saveDeletedMaps(ImageMapManager.java:286)
[18:38:08 WARN]:        at ImageFrame-1.7.10.0 (1).jar//com.loohp.imageframe.objectholders.ImageMapManager.close(ImageMapManager.java:104)
[18:38:08 WARN]:        at ImageFrame-1.7.10.0 (1).jar//com.loohp.imageframe.ImageFrame.onDisable(ImageFrame.java:322)
[18:38:08 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291)
[18:38:08 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237)
[18:38:08 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114)
[18:38:08 WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:550)
[18:38:08 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206)
[18:38:08 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[18:38:08 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[18:38:08 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:654)
[18:38:08 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:603)
[18:38:08 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:757)
[18:38:08 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:519)
[18:38:08 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:363)
[18:38:08 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230)
[18:38:08 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333)
[18:38:08 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[18:38:08 INFO]: [ImageFrame] ImageFrame has been Disabled!
```

```
[18:49:01 INFO]: Paper Plugins: (1):
[18:49:01 INFO]:  - BKCommonLib
[18:49:01 INFO]: Bukkit Plugins: (45):
[18:49:01 INFO]:  - BlockLocker, BlueMap, BMMarker, caramelPreventionTabComplete, Citizens, CoreProtect, Craftorithm, CustomCrops, DecentHolograms, Denizen
[18:49:01 INFO]:  Denizen, DiSky, Essentials, FastAsyncWorldEdit, ForcePack, FreedomChat, GSit, ImageFrame, ItemsAdder, LoneLibs
[18:49:01 INFO]:  LuckPerms, ModelEngine, MultiWorld, MythicMobs, ProtocolLib, *Reqn, *SharpSK, Shopkeepers, SkBee, Skellett
[18:49:01 INFO]:  SkJson, SkQuery, skRayFall, Skript, Skungee, *skUtilities, Vault, ViaBackwards, ViaVersion, Votifier
[18:49:01 INFO]:  VotingPlugin, *WebSK, *WebSKT, WorldEdit, WorldGuard
```

**Comment by LOOHP** [comment]
You might have corrupted the map color cache file. Try deleting it and restart. I think it is in your server root folder.

**Comment by newhajinyoon** [comment]
Thanks for fast answer! could you tell me where the root folder is? I'm sorry, I'm a beginner.

**Comment by newhajinyoon** [comment]
cuz its not in the C:\Users\Administrator\Desktop\Season1\survival\plugins\ImageFrame\data\deletedMaps.bin

![image](https://github.com/user-attachments/assets/72d67c26-24fa-4210-b242-85aaa0731ca8)

**Comment by LOOHP** [comment]
The root folder is the folder with your server jar.

**Comment by newhajinyoon** [comment]
Thx!! It worked
